jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - continue-on-error: true
      env:
        GRADLE_PUBLISH_MAVEN_PASSWORD: ${{ secrets.GRADLE_PUBLISH_MAVEN_PASSWORD }}
        GRADLE_PUBLISH_MAVEN_USER: ${{ secrets.GRADLE_PUBLISH_MAVEN_USER }}
        GRADLE_PUBLISH_REPO_URL: ${{ secrets.GRADLE_PUBLISH_REPO_URL }}
      name: Deploy with Gradle
      run: ./gradlew --no-daemon -Pversion=$(git tag --points-at HEAD) publish
name: Release
on:
  repository_dispatch:
    types: trigger-ga___release.yml
